include: package:lint/analysis_options.yaml
analyzer:
  exclude: [routes/routes/home/HomePage.dart]
  language:
    strict-raw-types: false
    
linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false
    
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false
    always_specify_types: false
    sized_box_for_whitespace: false
    avoid_print: false
    argument_type_not_assignable: false
    sort_pub_dependencies: false
    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    sort_constructors_first: true

    avoid_unnecessary_containers: false
    const_with_non_const: false
    invalid_constant: true
    # The new tabs vs. spaces. Choose wisely
    prefer_double_quotes: true

    # Good packages document everything
    public_member_api_docs: false
    
    omit_local_variable_types: false  

    file_names: false